#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC12B8E73B30F2FC8 (infra-root@openstack.org)
#
Name     : oslo.utils
Version  : 4.6.0
Release  : 80
URL      : http://tarballs.openstack.org/oslo.utils/oslo.utils-4.6.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.utils/oslo.utils-4.6.0.tar.gz
Source1  : http://tarballs.openstack.org/oslo.utils/oslo.utils-4.6.0.tar.gz.asc
Summary  : Oslo Utility library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.utils-license = %{version}-%{release}
Requires: oslo.utils-python = %{version}-%{release}
Requires: oslo.utils-python3 = %{version}-%{release}
Requires: debtcollector
Requires: iso8601
Requires: netaddr
Requires: netifaces
Requires: oslo.i18n
Requires: packaging
Requires: pbr
Requires: pyparsing
Requires: pytz
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : iso8601
BuildRequires : netaddr
BuildRequires : netifaces
BuildRequires : oslo.i18n
BuildRequires : packaging
BuildRequires : pbr
BuildRequires : pyparsing
BuildRequires : pytz
BuildRequires : six

%description
Team and repository tags
        ========================

%package license
Summary: license components for the oslo.utils package.
Group: Default

%description license
license components for the oslo.utils package.


%package python
Summary: python components for the oslo.utils package.
Group: Default
Requires: oslo.utils-python3 = %{version}-%{release}

%description python
python components for the oslo.utils package.


%package python3
Summary: python3 components for the oslo.utils package.
Group: Default
Requires: python3-core
Provides: pypi(oslo.utils)
Requires: pypi(debtcollector)
Requires: pypi(iso8601)
Requires: pypi(netaddr)
Requires: pypi(netifaces)
Requires: pypi(oslo.i18n)
Requires: pypi(packaging)
Requires: pypi(pbr)
Requires: pypi(pyparsing)
Requires: pypi(pytz)
Requires: pypi(six)

%description python3
python3 components for the oslo.utils package.


%prep
%setup -q -n oslo.utils-4.6.0
cd %{_builddir}/oslo.utils-4.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600109993
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.utils
cp %{_builddir}/oslo.utils-4.6.0/LICENSE %{buildroot}/usr/share/package-licenses/oslo.utils/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.utils/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
